function question(id, section, text, alteredText, answerType, options) {
  return {
    id,
    section,
    text,
    alteredText,
    answerType,
    options,
    answer: null,
  };
}

export const questions = [
  question(
    1,
    "Getting to know you",
    "What is your name?",
    "What label holds your regret?",
    "free-response",
  ),
  question(
    2,
    "Getting to know you",
    "How old are you?",
    "How much time do you have left?",
    "multiple-choice",
    [
      "17 or younger",
      "18-24",
      "25-34",
      "35-44",
      "45-54",
      "55-64",
      "65 or older",
    ],
  ),
  question(
    3,
    "Getting to know you",
    "What is your occupation?",
    "What is your main distraction?",
    "free-response",
  ),
  question(
    4,
    "The people in your life",
    "Who do you love the most?",
    "Who have you been too busy for?",
    "free-response",
  ),
  question(
    5,
    "The people in your life",
    "Who knows you best?",
    "Who are you performing for?",
    "free-response",
  ),
  question(
    6,
    "The people in your life",
    "Who would you call first if something went wrong?",
    "Who carries what you won't?",
    "free-response",
  ),
  question(
    7,
    "Your body and self",
    "When did you last feel fully present in your body?",
    "When did you last feel you deserved to be here?",
    "free-response",
  ),
  question(
    8,
    "Your body and self",
    "What is one way you've treated your body well today?",
    "How did you most recently need to convince yourself you're actually real?",
    "free-response",
  ),
  question(
    9,
    "Your body and self",
    "What is something you like about yourself?",
    "What do you hide behind?",
    "free-response",
  ),
  question(
    10,
    "What you're doing",
    "What do you do when you have free time?",
    "How do you avoid being truly alone with yourself?",
    "free-response",
  ),
  question(
    11,
    "What you're doing",
    "What do you spend most of your money on?",
    "What are you substituting for meaning?",
    "free-response",
  ),
  question(
    12,
    "What you're doing",
    "What is the last thing you do before bed?",
    "How will you spend your last moments?",
    "free-response",
  ),
  question(
    13,
    "What you're moving toward",
    "What is your main project right now?",
    "What are you doing to feel like you matter?",
    "free-response",
  ),
  question(
    14,
    "What you're moving toward",
    "What does your ideal life look like?",
    "When will you give yourself permission to start living?",
    "free-response",
  ),
  question(
    15,
    "What you're moving toward",
    "How are you going to make it happen?",
    "How are you going to make it happen?",
    "free-response",
  ),
];
